name: tic_tac_toe
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  socket_io_client: ^2.0.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/  # Make sure any additional images are in this directory

# Add the flutter_icons section here
flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"  # Path to your icon
